/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package patientform;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.sql.*; //imported all java classes for SQL 
/**
 *
 * @author Ather
 */
public class PatientFormGUI extends javax.swing.JFrame {

    /**
     * Creates new form PatientFormGUI
     */
    public PatientFormGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    
    //THIS CODE CAN BE IGNORED, IT IS JUST FOR FORMATTING! 
    private void initComponents() {

        patientInputField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        patientNameOutput = new javax.swing.JTextField();
        careCentreNameOutput = new javax.swing.JTextField();
        nurseInChargeOutput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        treatmentOutput = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        patientInputField.setText("Enter Patient ID Here");
        patientInputField.setName("patientIDINPUT"); // NOI18N
        patientInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientInputFieldActionPerformed(evt);
            }
        });

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Treatment ID - Treatment Name - Physcian ID - Date");

        jLabel2.setText("Patient Name:");

        jLabel3.setText("Care Centre Name:");

        jLabel4.setText("Nurse In Charge:");

        treatmentOutput.setColumns(20);
        treatmentOutput.setRows(5);
        jScrollPane1.setViewportView(treatmentOutput);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(patientInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(submitButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(careCentreNameOutput)
                            .addComponent(nurseInChargeOutput)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel1)
                                .addGap(22, 22, 22))
                            .addComponent(patientNameOutput)
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel3)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(patientInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(patientNameOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(careCentreNameOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(3, 3, 3)
                .addComponent(nurseInChargeOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void patientInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientInputFieldActionPerformed

       //when submit button get's requested
    //THIS is the important part
    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed

        
        String patientID = patientInputField.getText();
        int patientIDNumber = Integer.parseInt(patientID);
        try {
            //establish connection to database
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = 
                    DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "ather", "lemons");
            Statement st = con.createStatement();
            //Statement to get Patient, Care_centre and Nurse_in_Charge
            String sql1 = "SELECT PATIENTS.NAME Patient, CARE_CENTRES.NAME Care_Centre, NURSES.NAME Nurse_In_Charge\n" +
            "FROM PATIENTS,NURSES,CARE_CENTRES\n" +
            "WHERE " + patientID + " = PATIENTS.PID AND PATIENTS.CARE_CENTRE_ID = CARE_CENTRES.CID AND CARE_CENTRES.NURSE_CHARGE_ID = NURSES.NID";
            
            //statement to get Treatment information
            String sql2 = "SELECT TID TreatmentID, TREATMENT_NAME Treatment_Name, TREATMENTS.PHYSICIAN_ID PhysicianID, "
                    + "DATE_TREATMENT DateOfTreatment FROM TREATMENTS WHERE " + patientID + " = TREATMENTS.PATIENT_ID";
            

        //only one row for this query, just setting text fields to the columns
        ResultSet resultSet1 = st.executeQuery(sql1);
        while (resultSet1.next()) {
                patientNameOutput.setText(resultSet1.getString(1));
                careCentreNameOutput.setText(resultSet1.getString(2) + " Care Centre");
                nurseInChargeOutput.setText(resultSet1.getString(3));
        }
        
        //this is more complicated, as I do not know how many rows I will have for each patient
        //I will print out the results, and create a Stream to capture these print outs
        ResultSet resultSet = st.executeQuery(sql2);
        ResultSetMetaData rsmd = resultSet.getMetaData();
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        PrintStream ps = new PrintStream(baos);
        PrintStream old = System.out;
        System.setOut(ps);
        int columnsNumber = rsmd.getColumnCount();
        //this loop will iterate through the rows, and add them to the stream
          while (resultSet.next()) {
            for (int i = 1; i <= columnsNumber; i++) {
                if (i > 1) System.out.print(" - ");
                String columnValue = resultSet.getString(i);
                System.out.print(columnValue);
                }
            System.out.println("");
        }
        
        //I will flush the stream, and revert back to standard output stream
        System.out.flush();
        System.setOut(old);
        
        //I will take the contents of the stream during the loop, and set it to the text area
        treatmentOutput.setText(baos.toString());

        //close the connection to the database
        con.close();

        //we are done! 
        }
        catch (Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientFormGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientFormGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientFormGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientFormGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientFormGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField careCentreNameOutput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nurseInChargeOutput;
    private javax.swing.JTextField patientInputField;
    private javax.swing.JTextField patientNameOutput;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextArea treatmentOutput;
    // End of variables declaration//GEN-END:variables
}
