#!/bin/sh
#pyramid - makes a number pyramid given an integer input
#Top part of Triangle
i=1
while [ $i -le $1 ]
do
    j=0
    while [ $j -lt $i ]
    do
	      value=`expr 0 + $j`
	      printf "$value "
	      j=`expr $j + 1`
    done
    i=`expr $i + 1`
    echo
done
#Bottom Part of Triangle
i=`expr $1 - 1`
while [ $i -gt 0 ]
do
    j=0
    while [ $j -lt $i ]
    do
	      value=`expr 0 + $j`
	      printf "$value "
	      j=`expr $j + 1`
    done
    i=`expr $i - 1`
    echo
done
